### ISSUE TITLE
Does not support 6mb/8mb roms that use SA-1.

### ISSUE THREAD

**Issue by ChoroGalaxiaJr** [SarahH12099/MeSNEmu#2]

**Comment by ChoroGalaxiaJr** [comment]
The newest SNES9X supports 6mb/8mb roms, it might be due to an outdated version of the emulator. This makes certain mario world hacks simply crash on startup.

**Comment by SarahH12099** [comment]
MeSNEmu v1.4.6.2+ added first support for 6mb/8mb roms, so it should work just fine if you are using v1.4.6.2 and above. What version are you using please?

**Comment by ChoroGalaxiaJr** [comment]
MeSNEmu 1.4.5.6, got it from the reddit post.

**Comment by SarahH12099** [comment]
Please update to MeSNEmu v1.4.6.3 and it should work, sorry, forgot to update the reddit post

**Comment by ChoroGalaxiaJr** [comment]
Updated to v1.4.6.3, Still a black screen.

**Comment by SarahH12099** [comment]
Can you send the rom you are using please? It maybe because I fixed the rom size thing but didn't add support for the rest of the Snes9x hacks commit they did because of errors

**Comment by ChoroGalaxiaJr** [comment]
The 9th Annual Vanilla Level Design Contest: Collaboration Hack
https://www.smwcentral.net/?p=section&a=details&id=14812

https://cdn.discordapp.com/attachments/507315403010211860/571156117091123220/VLDC9.smc (remove if required)

**Comment by SarahH12099** [comment]
Thank you, I will look into it, its probably just that I haven't implemented Snes9x's new rom hack compatibility because of errors in it on Xcode.

**Comment by ChoroGalaxiaJr** [comment]
Alright, if it helps, the version that supports 8mb roms properly is 1.54 (and higher), the lower ones only support 6mb roms, but emulate it incorrectly.

**Comment by SarahH12099** [comment]
Question did you convert the bps to smc?

**Comment by ChoroGalaxiaJr** [comment]
Yeah, using floating IPS. https://www.smwcentral.net/?p=section&a=details&id=11474

**Comment by SarahH12099** [comment]
In my latest commit (no release yet), I did fix the game not working but saves and save states are broken for it, so it will require a little bit more work for it to be fully working on MeSNEmu.
![IMG_1382](https://user-images.githubusercontent.com/43968044/56827160-05670c80-682c-11e9-8c8c-87fec719097c.PNG)

**Comment by SarahH12099** [comment]
I have fixed the save issue and the rom is now completely working. Please know when v1.4.6.4 is released, you will have to press Reset in the menu in the game to restart the rom and get rid of the corrupted save it made.
